---
- name: Get IPA users groups
  hosts: teste
  gather_facts: false

  vars:
    user_groups: []

  tasks:
    - name: IPA server login
      uri:
        url: "https://master.petros-poc.com/ipa/session/login_password"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Referer: "https://master.petros-poc.com/ipa"
          Accept: "text/plain"
        validate_certs: no
        body_format: form-urlencoded
        body:
          user=admin&password=Petrobras
      register: results

    -  name: debug
       debug:
         var: results.cookies.ipa_session

    - name: IPA server get Groups
      uri:
        url: "https://master.petros-poc.com/ipa/session/json"
        method: POST
        headers:
          Content-Type: "application/json"
          Referer: "https://master.petros-poc.com/ipa"
          Accept: "application/json"
          Cookie: "ipa_session={{ results.cookies.ipa_session }}"
        validate_certs: no
        body_format: json
        body:
          {"method":"group_find", "params":[[],{"user":"{{ user_name}}","all": false}]}
      register: results

    -  name: debug
       debug:
         var: results.json.result.count

    - name: lista groups
      set_fact:
        user_groups: "{{ user_groups +  [item.cn[0]] }}"
      with_items:
         "{{ results.json.result.result }}"

    - name: debug
      debug:
         var: user_groups

    - name: Removing user from group
      community.general.ipa_group:
         name: "{{ item }}"
         user:
         - "{{ user_name }}"
         append: yes
         state: absent
         ipa_host: master.petros-poc.com
         ipa_user: admin
         ipa_pass: Petrobras
      loop: "{{ user_groups }}"
      when:
          item  != "ipausers"