---
- name: Windows server
  hosts: windows
  gather_facts: no

  tasks:

  - name: Change Windows Registry 
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\policies\Explorer
      name: NoDriveTypeAutoRun
      data: 0x000000ff
      type: dword
