---
- name: Windows server
  hosts: windows

  tasks:
    - name: Ensure user bob is present
      ansible.windows.win_user:
        name: bob
#        password: B0bP4ssw0rd
        password: "{{ user_password }}"
        state: present
        groups:
           - Users


    - name: Create a local profile for an account.
      win_user_profile:
        username: "{{ user_name}}"
        state: present

    - name: Create a new local group.
      win_group:
        name: developers
        description: Developers Group
        state: present

