---
- name: Windows server
  hosts: windows

  tasks:
    - name: Ensure user bob is present
      ansible.windows.win_user:
        name: bob
        password: B0bP4ssw0rd
        state: present
        groups:
           - Users


  - name: Create a local profile for an account.
    win_user_profile:
      username: bob
      state: present
